server:
  port: 8080
  servlet:    context-path: /demo
 
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/wxmini?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml
  type-aliases-package: top.wx.pojo
 
#showSql
